[project]
name = "igrep"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "numpy>=2.4.2",
    "pillow>=12.1.1",
    "pytesseract>=0.3.13",
    "sentence-transformers>=5.2.3",
    "sqlalchemy>=2.0.48",
]
