[project]
name = "igrep"
version = "0.1.0"
description = "i-grep for pattern and semantic seach."
readme = "README.md"
requires-python = ">=3.13"
authors = [
    {name = "Yash Dhadod", email = "yashdhadod@gmail.com"}
]
license = {text = "MIT"}
keywords = ["search", "ocr", "image", "pdf", "semantic-search", "cli"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Topic :: Utilities",
]
dependencies = [
    "numpy>=2.0",
    "onnxruntime>=1.18",
    "pillow>=10.0",
    "platformdirs>=4.0",
    "pymupdf>=1.24",
    "pytesseract>=0.3.13",
    "sqlalchemy>=2.0",
    "tokenizers>=0.19",
]
[project.scripts]
igrep = "src.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"
